### ISSUE TITLE
Extra parameter in "maximum power exceeded" warning

### ISSUE THREAD

**Issue by hdtodd** [JoToSystems/LoraPacketForwarder#1]
The following line has a duplicated (last) parameter (generates a compiler warning), I think, in the code section that matches tx power:

                    MSG("WARNING: power for TX - %d exceeding maximum power - , use maximum power - %d\n", txpkt.rf_power, txlut.lut[txlut.size - 1].rf_power, txlut.lut[txlut.size - 1].rf_power);

**Comment by tonysmith55** [comment]
Thank you David I will have a look.  I think this problem is in the original code and not introduced by the change I made.  What is the power in the last entry in your global_conf.json file?

**Comment by hdtodd** [comment]
The last entry is:
        "tx_lut_15": {
                "desc": "TX gain table, index 15",
                "pa_gain": 3,
                "mix_gain": 14,
                "rf_power": 27,
                "dig_gain": 0
        }

**Comment by hdtodd** [comment]
And you may be right ... that compiler warning might have come up before and I just didn't notice it.

**Comment by tonysmith55** [comment]
How are you getting a compiler warning with my code as its already compiled?  I will have a look at the original Semtech code and assume this is warning you get when you start the packet forwarder.

**Comment by hdtodd** [comment]
Ah, I'm compiling the source code.  Thought you were modifying that section of lora_pkt_fwd.c.  Sorry.
